[package]
name = "solana-docs-examples"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
solana-cli-config = "2.2.0"
solana-client = "2.2.0"
solana-sdk = "2.2.1"
spl-associated-token-account = "6.0.0"
spl-token = "7.0.0"
spl-token-2022 = "7.0.0"
